### ISSUE TITLE
No GPS FIX

### ISSUE THREAD

**Issue by cvanaalst** [noppingen/Lora-TTNMapper-T-Beam-v10#4]
Hi,

I installed your software on my TTGO TBEAM  (T22 v1.0 20190612) - I cannot get a GPS fix;  connection to TTN works fine (I forced checkGpsFix() to true - and it sends packages).
I know that the GPS works; I have installed Meshtastic (pre-built binary) on the TTGO and the GPS worked - but I have been trying various GPS examples (TinyGPS & TinyGPS++) , but I cannot get a fix ?
So I assume it has something to do with the wrong TinyGPS++.h library or board. I am trying to figure out how I can see whether I have really no fix or whether I am not communicating with the NEO M8N GPS chip.
I have 2 TTGO's , bith give me the same result. (one T22 v1.0 20190612 and one T22 v1.1 20191212)

added on 3/7/2020: I have discovered that I am not getting any data from the GPS: I am getting the "GPS INIT", but I am not getting any '.' printed, so I assume that the serial connection is not available ?

`void gps::init() {
  GPSSerial.begin(9600, SERIAL_8N1, GPS_TX, GPS_RX);
  GPSSerial.setTimeout(2);
  Serial.println("GPS INIT !");
}

void gps::encode() {       
    int data;
    unsigned long previousMillis = millis();

    while((previousMillis + 100) > millis()) {
        while (GPSSerial.available() ) {
            char data = GPSSerial.read();
            tGps.encode(data);
            //Serial.print(data);
            Serial.print(".");
        }
    }
    Serial.println("");
}`

any help is usefull

regards,

Chris

**Comment by schroepfer** [comment]
I have exactly the same Problem!

**Comment by cvanaalst** [comment]
I've ordered 2 new T22 v1.0 20190612 boards with the NEO -6M (older type - I had the M8N) GPS and I get exactly the same issue; the GPS is not responding - again a pre-built Meshtastic binary is working (good GPS fix), but not my own compiled version.
So it must be a library-issue ...
Can you provide me with the exact library versions you use ? On a seperate PC I will install a fresh Arduino and all the lib's ...

Chris

**Comment by schroepfer** [comment]
..i think, noppingen is no more working on this project

**Comment by cvanaalst** [comment]
well, it's a pity; there must be a library issue: I have installed PlatformIO (planning to do that for quite some time) and I am trying to get the GPS working on the T-beam. Whatever example I try it is not working ....
I inistalled the Meshtastic project in PlatformIO and I am trying to go thru the code to see what is different ... must be something stupid ...
Advantage of PlatformIO is that you can have different libs (& versions) per project, this will allow me to test several diff lib-versions ...
@schroepfer if you get it to work, let me know !
Chris

**Comment by schroepfer** [comment]
I did the same, like you! Only Meshtastic work.
